<template>
  <div class="content">
    <div class="md-layout">
      <div class="md-layout-item md-medium-size-100 md-xsmall-size-100 md-size-100">
        <md-card>
          <md-card-header data-background-color="green">
            <h4 class="title">View Jobs</h4>
            <p class="category">Jobs Generated by Clients</p>
          </md-card-header>
          <md-card-content>
             <md-table v-model="searched" md-card md-fixed-header>
                <md-table-toolbar>
                    <div class="md-toolbar-section-start">
                    <h1 class="md-title">Jobs</h1>
                    </div>

                    <md-field md-clearable class="md-toolbar-section-end">
                    <!-- <md-input placeholder="Search by categories..." v-model="search" @input="searchOnTable" /> -->
                    </md-field>
                </md-table-toolbar>


                <md-table-row slot="md-table-row" slot-scope="{ item }">
                    <!-- <md-table-cell md-label="ID" md-sort-by="id" md-numeric>{{ item.id }}</md-table-cell> -->
                    <md-table-cell md-label="Created on" md-sort-by="status">{{ item.created_on }}</md-table-cell>
                    <md-table-cell md-label="Created By" md-sort-by="created-by">{{ getJobCreator(item.created_by) }}</md-table-cell>
                    <!-- <md-table-cell md-label="Status" md-sort-by="status">{{ item.status }}</md-table-cell> -->
                    <md-table-cell md-label="Status" md-sort-by="status"> <h5><b-badge :variant="item.status=='Opened'? 'primary':'success'">{{ item.status }}</b-badge></h5> </md-table-cell>

                    <md-table-cell md-label="Action" md-sort-by="action">  
                        <md-button class="md-dense md-raised md-primary btn-sm"  @click="setUser(item)">View</md-button>
                    </md-table-cell>
                </md-table-row>
                </md-table>
                 <b-modal id="modal-1"  hide-footer>
                   <template v-slot:modal-header>
                      <h5 class="ml-auto mr-auto"> <b>Job Categories </b></h5>
                    </template>
                   <b-container >
                     <div class="row">
                       <div class="col-md-6">
                        <h6> <b>Created on </b> </h6>
                       </div>
                       <div class="col-md-6">
                        <p>{{selected_user.created_on}}</p> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <h6> <b>Created By </b> </h6>
                       </div>
                       <div class="col-md-6 mt-2">
                        <p>{{getJobCreator(selected_user.created_by)}}</p> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <h6><b>Type</b>   </h6> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <p>{{selected_user.type}} </p> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <h6> <b>Status </b> </h6> 
                       </div>
                       <div class="col-md-6 mt-2">
                         <p>{{selected_user.status}}</p>
                       </div>
                       <div class="col-md-6 mt-2">
                        <h6><b>Location </b> </h6> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <p>{{selected_user.location}}</p> 
                       </div>
                       <div class="col-md-6 mt-2">
                        <h6><b>Description</b> </h6> 
                       </div>
                       <div class="col-md-6 mt-2">
                       <p>{{selected_user.description}}</p> 
                       </div>
                     </div>
                   </b-container>
                   <b-container fluid class="mt-4">
                      <!-- <md-button class="ml-2 md-dense md-raised md-primary pull-right" >Update</md-button> -->
                      <md-button class="md-dense md-raised md-primary pull-right" @click="hide">Cancel</md-button>


                   </b-container>
                </b-modal>
          </md-card-content>
        </md-card>
      </div>

      <div
        class="md-layout-item md-medium-size-100 md-xsmall-size-100 md-size-100"
      >
      
      </div>
    </div>
  </div>
</template>
<script>
import {mapGetters} from 'vuex'
const toLower = text => {
    return text.toString().toLowerCase()
  }

  const searchByName = (items, term) => {
    if (term) {
      return items.filter(item => toLower(item.category_name).includes(toLower(term)))
    }

    return items
  }

// import { SimpleTable, OrderedTable } from "@/components";

export default {
    data: () => ({
      search: null,
      selected_user:'',
      searched: [],
      showDialog: false,
    }),
    watch:{
      clients(){
        if(this.clients.length>0){
          console.log(this.clients)
          // this.searched = this.clients

        }
      },
      jobs(){
        if(this.jobs.length>0){
        this.searched = this.jobs

        }
      }

    },
    computed:{
      ...mapGetters({jobs:'jobs',users:'clients'})
    },
    methods: {
      getJobCreator(id) {
        let temp_user=this.users.find(user_item=>user_item.id==id)
        if(temp_user==null){
          return 'NA'
        }
        else{
        return temp_user.first_name + ' ' +temp_user.last_name
        }
      },
      setUser(item){
        this.selected_user=item
        this.$bvModal.show('modal-1')	
      },
      hide(){
        this.$bvModal.hide('modal-1')	
      },
      newUser () {
        window.alert('Noop')
      },
      searchOnTable () {
        this.searched = searchByName(this.users, this.search)
      }
    },
    created () {
      this.searched = this.jobs
      // console.log(this.users)
    }
  }
</script>

<style scoped>


</style>
